### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by RobotGyal** [RobotGyal/ZANK#17]
fix the routes for login page to not go to non-existent profile page

**Comment by UPstartDeveloper** [comment]
Hey team, good news!
I just fixed the login redirect, currently the site will now redirect you to the _home _page_ after you sign in. 

However, I think we should still focus on making **specialized UI's** (i.e. the buttons in the navbar change) based on user authentication.

**Especially**, we should prioritize making it so a logged in user can see a button in the navbar to see their profile page, because that's (currently) where we'll need them to specify what kind of user they are - an architect, or a compliance officer.

Hey @KabsaA , can you help with this? Let's use this opportunity to grow our Jinja2 skills!

**Comment by RobotGyal** [comment]
implemented
